### ISSUE TITLE
Dynamic (wallpaper) color scheme

### ISSUE THREAD

**Issue by VasilisKos** [quicksc0p3r/simplecounter#11]
Add an option for dynamic color scheme of the app (pick it from the current wallpaper). This is possible at least from Android 11 (I use Android 11, and have several apps that have that feature).

**Comment by quicksc0p3r** [comment]
Dynamic color is only supported on Android 12+. If you're running an older version of Android, you can pick from 6 predefined color schemes in the app and choose the one that best matches your wallpaper.

**Comment by VasilisKos** [comment]
> Dynamic color is only supported on Android 12+. If you're running an older version of Android, you can pick from 6 predefined color schemes in the app and choose the one that best matches your wallpaper.

As I told you I have several apps that have a way to implement it. One is Unitto, the one I've mentioned before.
Anyway, it's up to you...
