### ISSUE TITLE
[Feature] Haptic feedback

### ISSUE THREAD

**Issue by VasilisKos** [quicksc0p3r/simplecounter#2]
Would be nice to add a setting to enable haptic feedback whenever + or - is tapped in counters.

**Comment by quicksc0p3r** [comment]
This feature was implemented and will be part of the next release!

**Comment by VasilisKos** [comment]
> This feature was implemented and will be part of the next release!

Thanks! Please don't make the next release until I translate the new strings. Will make a pull request soon.

**Comment by VasilisKos** [comment]
In the new 1.1 version the haptic feedback works only when haptic is activated in Android settings for every touch of the screen. It shouldn't be this way. It should be working when enabled in the app, like many apps do. Please fix it.

**Comment by quicksc0p3r** [comment]
> In the new 1.1 version the haptic feedback works only when haptic is activated in Android settings for every touch of the screen. It shouldn't be this way. It should be working when enabled in the app, like many apps do. Please fix it.

Doing it that way would require vibrator permission. The goal is to have the least amount of permissions.

**Comment by VasilisKos** [comment]
> > In the new 1.1 version the haptic feedback works only when haptic is activated in Android settings for every touch of the screen. It shouldn't be this way. It should be working when enabled in the app, like many apps do. Please fix it.
> 
> Doing it that way would require vibrator permission. The goal is to have the least amount of permissions.

Sorry, but the goal is to have a great, functional app. Vibration permission is not that big deal. Has no security issues.
