### ISSUE TITLE
F-Droid build not reproducible

### ISSUE THREAD

**Issue by linsui** [quicksc0p3r/simplecounter#24]
[org.quicksc0p3r.simplecounter_1001002.apk.html.zip](https://github.com/quicksc0p3r/simplecounter/files/14622487/org.quicksc0p3r.simplecounter_1001002.apk.html.zip)

Some lines have different order. Could you please try clean cache and rebuild the apk? Thanks!

**Comment by quicksc0p3r** [comment]
Hi, what do you mean by "clear cache"?

**Comment by quicksc0p3r** [comment]
Also could this be related to the ProGuard rules I have added?

**Comment by linsui** [comment]
You can run gradlew clean before build.

> Also could this be related to the ProGuard rules I have added?

No idea. But we use the same rules anyway.

**Comment by quicksc0p3r** [comment]
[Fixed!](https://gitlab.com/quicksc0p3r/fdroiddata/-/jobs/6409021663)

**Comment by linsui** [comment]
Thanks!

**Comment by licaon-kter** [comment]
can you reopen?

ref: https://monitor.f-droid.org/builds/log/org.quicksc0p3r.simplecounter/1002002#site-footer

because of: https://github.com/quicksc0p3r/simplecounter/commit/89d7a01abbd3b38956e3bb16196ab09bb8cfb0b7

**Comment by quicksc0p3r** [comment]
I implemented this temporary (workaround)[https://github.com/quicksc0p3r/simplecounter/commit/5c9fcddcb6d74e68fc3e765cd34dd3ad92cfdc78] to hopefully fix the problem. Seems like a problem on your end, since on my machine it builds fine.

**Comment by licaon-kter** [comment]
What I don't get, why use a root folder for the schemas? Instead of a relative one like it used to? Or did I read that wrong?

**Comment by quicksc0p3r** [comment]
Maybe it behaves differently on Linux and Windows, but on my machine it creates a `schemas` folder within the project folder and everything works as intended.

**Comment by licaon-kter** [comment]
Can be closed I guess
