### ISSUE TITLE
AlertDialog disappears on uiMode change

### ISSUE THREAD

**Issue by nicolarevelant** [quicksc0p3r/simplecounter#39]
# Problem: when I perform this sequence of events the AlertDialog disappears:

1. Touch the floating button
2. Switch between light and dark mode twice

or:

1. Create a counter
2. Touch a counter's 3-dot icon at the top right
3. Touch Edit
4. Switch between light and dark mode twice

or:

1. Create a counter
2. Touch a counter's 3-dot icon at the top right
3. Touch Delete
4. Switch between light and dark mode twice

or:

1. Create a counter
2. Touch a counter
3. Touch the edit icon at the top
4. Switch between light and dark mode twice

or:

1. Create a counter
2. Touch a counter
3. Touch the delete icon at the top right
4. Switch between light and dark mode twice

or:

1. Touch the 3-dot icon at the top right
2. Touch Settings
3. Touch one of the following:
    1. Theme
    2. Color scheme
    3. Haptic feedback
4. Switch between light and dark mode twice

# Possible solution:

- app/src/main/java/org/quicksc0p3r/simplecounter/ui/screens/Main.kt
- use rememberSaveable instead of remember in the following variables:
    - counterForDialog
    - counterCreationDialogOpen
    - counterEditDialogOpen
    - counterDeleteDialogOpen
- app/src/main/java/org/quicksc0p3r/simplecounter/ui/screens/FullscreenView.kt
- use rememberSaveable instead of remember in the following variables:
    - editDialogOpen
    - deleteDialogOpen
- app/src/main/java/org/quicksc0p3r/simplecounter/ui/screens/Settings.kt
- use rememberSaveable instead of remember in the following variables:
    - lightDarkDialogOpen
    - colorSettingDialogOpen
    - hapticFeedbackDialogOpen

# Screenshots:

<img src="https://github.com/user-attachments/assets/57a3c7ae-25ae-4f5b-8550-5016e4f65885" width="30%">
<img src="https://github.com/user-attachments/assets/a70d9242-70db-4e94-9799-cb1fe2f13521" width="30%">

# Version:

1.1.4 (1001004) - not fixed in 1.2.4

**Comment by quicksc0p3r** [comment]
Partial fix for creation, setting and contributors dialogs has been implemented. It's better to have the edit and delete dialogs close for now

**Comment by quicksc0p3r** [comment]
A fix was implemented for the rest of the dialogs.
