### ISSUE TITLE
Add Croatian (hr) to translation project

### ISSUE THREAD

**Issue by anotherus3r** [quicksc0p3r/simplecounter#42]
Hi, could you please add Croatian (hr) to the translation project?

**Comment by quicksc0p3r** [comment]
Hi, please use `+` button to start a new translation.
![image](https://github.com/user-attachments/assets/41a135aa-19c7-440a-84cb-b61ce6b7d903)

**Comment by anotherus3r** [comment]
Hi, I did add it now but it says there's 0 strings to translate.

**Comment by quicksc0p3r** [comment]
Can you please edit `values-hr/strings.xml` manually and submit a pull request?

**Comment by anotherus3r** [comment]
Hi @quicksc0p3r, sorry for the delay. I submitted #44 as you requested. :)
