### ISSUE TITLE
Not readable font color in "About" page

### ISSUE THREAD

**Issue by VasilisKos** [quicksc0p3r/simplecounter#5]
The font color of the last text line in the "About" page, when in dark mode, is black in dark background. Thus, it's not readable. See the screenshot:

![Screenshot_20231125-222412](https://github.com/quicksc0p3r/simplecounter/assets/12777771/26bb2e89-117c-40c1-b49f-d4b1361a8069)

**Comment by quicksc0p3r** [comment]
Thanks for the report, fix will be part of next release
